server/config/routes.rb
Server::Application.routes.draw do
  get "welcome/index"

  resources :images do
    collection do
      get 'ranking'
    end
  end
  resources :vote do
    collection do
      post 'thumbdown'
    end
  end

  root :to => 'welcome#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout

end

server/app/models/image.rb
class Image < ActiveRecord::Base
  has_many :votes
  attr_accessible :caption, :path
  def voted?(id)
    self.votes.any? {|v| v.user.id == id}
  end
  def votedby(id)
    self.votes.each {|v| return v if v.user.id == id}
  end
end

server/app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes
  attr_accessible :name, :provider, :uid, :fb_user_id, :email
  def self.find_or_create_from_auth_hash(auth_hash)
    user_data = auth_hash.extra.raw_info
    if user = User.where(:uid => user_data.id).first
      user
    else # Create a user with a stub password.
      User.create!(:uid => user_data.id, :name => user_data.name, :email => user_data.email)
    end
  end
end

server/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
  attr_accessible :comment, :image_id, :user_id, :num
  def vto_s
    (num == 1) ? "+" : "-"
  end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

server/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id], :include => :votes, :order => "created_at desc")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
  def ranking
    @images = Image.joins(:votes).select('images.*, sum(votes.num) as "cnt"').group(:image_id).order(' cnt desc').limit(10)
  end
end

server/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to '/'
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

server/app/controllers/vote_controller.rb
class VoteController < ApplicationController
  def create
    uid = current_user.id
    unless (Vote.find(:first, :conditions => {:image_id => params[:image_id], :user_id => uid}))
      @vote = Vote.create(:image_id => params[:image_id], :user_id => uid, :num => 1)
    end
    respond_to do |format|
      format.html { render :layout => false }
      format.js
    end
  end
  def update
    @vote = Vote.find(params[:id])
    @vote.comment = params[:vote][:comment]
    @vote.save
    respond_to do |format|
      format.html { render :layout => false }
      format.js
    end
  end
  def thumbdown
    uid = current_user.id
    unless (Vote.find(:first, :conditions => {:image_id => params[:image_id], :user_id => uid}))
      @vote = Vote.create(:image_id => params[:image_id], :user_id => uid, :num => 0)
    end
    redirect_to :controller => :welcome
  end
end

server/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    images = Image.joins("LEFT OUTER JOIN votes ON images.id = votes.user_id").find(:all)
    if (current_user)
      images.delete_if {|i| i.votes.select{|v| v.user_id == current_user.id}.count > 0}
    end
    if images.count > 0
      offset = rand(images.size)
      @image = images[offset]
      @votes = @image.votes.sort{|a,b| a.created_at <=> b.created_at}
      #@count = @image.votes.inject(0) { |sum,elem| sum + elem.num }
    else
      @image = nil
      @votes = []
      @count = 0
    end
    @voted = false;
    if (current_user)
      myid = current_user.id
      @votes.each do |v|
       if (v.user_id == myid)
         @voted = true
         @myvote = v
         break
       end
      end
    end
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/images_helper.rb
module ImagesHelper
end

server/app/helpers/vote_helper.rb
module VoteHelper
end

server/app/helpers/welcome_helper.rb
module WelcomeHelper
end

server/app/views/images/_form.html.erb
<%= form_for @image, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :caption, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :caption, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn' %>
  </div>
<% end %>

server/app/views/images/_vote.html.erb
<div>
<%if current_user%>
  <%if @image.voted?(current_user.id)%>
    You have voted(<%=@image.votedby(current_user.id).vto_s%>)<br/>
    <%=@image.votedby(current_user.id).comment%>
  <%elsif @image == nil%>
    There is no images to vote.
  <%else%>
  <div class="votearea">
    <%= link_to 'I found face!', {:controller => :vote, :action => :create, :image_id => @image.id}, :remote => true, :method => :post, "data-type" => "html", :class => 'btn btn-primary vote' %>
    <%= link_to 'No, there is no face', {:controller => :vote, :action => :thumbdown, :image_id => @image.id}, :method => :post, :class => 'btn btn-inverse' %>
  </div>
  <div id="response_div"></div>
  <%end%>
<%else%>
  Need login to vote
<%end%>
</div>
<%= javascript_tag do %>
$('a.vote').bind('ajax:success', function(evt, data, status, xhr){
  $('#response_div').html(data);
  $('a.vote').html('You voted')
});
function reload(){
  location.reload();
}
<% end %>

server/app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:caption) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.id, image_path(image) %></td>
        <td><%= image.caption %></td>
        <td><%=l image.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %>

server/app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

server/app/views/images/ranking.html.erb
<style>
  li {
    padding:6px;
    width:300px;
    list-style:none;
  }
</style>
<ul>
<% @images.each do |image| %>
  <li><%= image.cnt %> voted:<br/><%=link_to image_tag(image.path), :controller => :images, :action => :show, :id => image.id %></li>
<% end %>
</ul>

server/app/views/images/show.html.erb
<div class="page-header">
  <h1><%= @image.caption %></h1>
</div>

<%= render "vote" %>

<dl class="dl-horizontal">
  <dt><strong><%= image_tag @image.path %></strong></dt>
</dl>

<ul class="unstyled">
<% @image.votes.each do |v| %>
  <% if (v.comment)%>
    <li >
    <div class="comment"><%=v.comment%></div>
    <div class="timeandname">
      <abbr class="timeago" title="<%= v.created_at.getutc.iso8601 %>">
        <%= v.created_at.to_s %>
      </abbr>
      by <%=v.user.name%>
    </div>
    </li>
  <% end %>
<% end %>
</ul>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    {:controller=>:images, :action => :ranking}, :class => 'btn'  %>
</div>
<%= javascript_tag do %>
  jQuery(document).ready(function() {
    jQuery("abbr.timeago").timeago();
    });
<% end %>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= javascript_include_tag "application" %>
    <title><%= content_for?(:title) ? yield(:title) : "Marsface Project" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Marsface Project</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li>
              <% if current_user %>
                Welcome, <%= current_user.name %>! <%= link_to "Logout", logout_url %>
              <% else %>
                <%= link_to "Sign in with Facebook", "/auth/facebook" %>
              <% end %>
              </li>
              <li>
              <%= link_to "Ranking", {:controller => :images, :action => :ranking} %>
              </li>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Marsface project</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>

server/app/views/vote/create.html.erb
<%= form_for([@vote], :remote => true) do |f| %>
  <%= f.text_field :comment %>
  <%= f.submit "Comment" %>
<% end %>

server/app/views/vote/update.html.erb
$("#response_div").html("<%=@vote.comment%>");
setTimeout("reload()", 100);

server/app/views/welcome/index.html.erb
<h1>Geoface: Find aliens' footprints</h1>
<p>Can you find a face in the below image? It might an object which is built by aliens!</p>
<div class="vcount">Voted count:<%=@votes.count%></div>
<div>
  <%= render '/images/vote' %>
</div>
<hr/>
<% if (@image) %>
<%=image_tag(@image.path)%>
<% end %>